const stage = document.getElementById("cg-bg-animation-s3");
const words = [
  "CAGE",
  "CONVENE",
  "CARPE DIEM",
  "CHAFF",
  "COFFERS",
  "CRAFT",
  "COALESCE",
  "CHISEL",
  "CANYTY",
  "CONVIVIAL",
  "CHUFFED",
  "CUNCTATION",
  "COMPILE",
  "CRIPPLE",
  "COOKING",
  "CLAP",
  "CONDITION",
  "CRITERIA",
  "CANDLE",
  "CROP",
  "CHALKED",
  "CHORES",
  "CEDE",
  "CRADLE",
  "COMMISSION",
  "CHRISTEN",
  "CONFIRM",
  "CIRCUMSTANCES",
  "COMMAND",
  "CLOSER",
  "CONCUR",
  "CONFIDE",
  "CRAZY",
  "CORROSION",
  "COMOT",
  "CLOTHES",
  "CRY",
  "CYCLE",
  "CONCEIVE",
  "CRACK",
  "CROWN",
  "COMFORTABLE",
  "COMPANION",
  "CLARIFY",
  "COMPRISE",
  "CONSTANT",
  "CHASE",
  "CONSTRUCT",
  "CLAMOR",
  "CEMENT",
  "COMPASSION",
  "CROMULENT",
  "COACH",
  "CODE",
  "COMPROMISE",
  "CUE",
  "CONTAGIOUS",
  "CISTERN",
  "CRAWL",
  "COMMENDATION",
  "COUNTENANCE",
  "CLEANLINESS",
  "COLOR",
  "CHAMBER",
  "CHARGE",
  "CUTE",
  "COMPETENT",
];

words.forEach((word) => {
  const element = document.createElement("span");
  element.textContent = word;
  stage.appendChild(element);
});
